# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-ConceptSearch
version:      0.03
version_from: lib/Class/DBI/ConceptSearch.pm
installdirs:  site
requires:
    Class::DBI:                    0.94
    XML::XPath:                    1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
